//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(schema_name = "app", table_name = "attendance_logs")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub scanner_uid: i32,
    pub check_time: DateTimeWithTimeZone,
    pub verify_type: i32,
    pub status: i32,
    pub source: String,
    pub created_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
