//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

pub use super::attendance_logs::Entity as AttendanceLogs;
pub use super::departments::Entity as Departments;
pub use super::employees::Entity as Employees;
